### PR TITLE
made suffix a keyword argument

### PR DESCRIPTION
**Pull request by vortexkd**
I'm trying to use the backlog api with at backlog.com but currently, backlog.jp is a fixed url.
Would you be willing to use something like this to make the url flexible?

### CODE REVIEW

**Comment by koxudaxi** [comment]
@vortexkd 
Thank you for creating this issue.
This client is generated by this code generator 

https://github.com/koxudaxi/BacklogPy/blob/6d66932fcc90afda1bb3201d52c0a481bacab822/api_generator/api_generator.py#L65-L68

There is how to generate code.
https://github.com/koxudaxi/BacklogPy#generating-the-backlog-api-v2-client

Would you please change `api_generator.py` and generate code?

**Comment by koxudaxi** [comment]
@vortexkd 
I merged this PR and updated `api_generator.py`.
Also, I have released a new version 1.1.0 :tada:

**Comment by vortexkd** [comment]
thank you! apologies for the delay was going to do it on the weekend

**Comment by koxudaxi** [comment]
No problme. Thank you very much!!

**Pull request merged**
